// Adds all these statuses to the database

// Imports
import { MongoClient } from 'mongodb';
import { config } from 'dotenv';

// Do the stuff
async function main() {

  config();

  const client = new MongoClient( process.env.RDS );
  await client.connect()

  if ( !client ) {
    console.error( 'Database connection failed!' );
    process.exit( 1 );
  }

  const db = client.db( 'FishsticksOnline' );

  const statusObjects = [
    { name: 'Contemplating 42.', type: 'custom' },
    { name: 'Why are you looking at my status?', type: 'custom' },
    { name: 'for /help', type: 'watching' },
    { name: `Skye's eyes only.`, type: 'custom' },
    { name: `My eyes are up here, forehead. Actually...I don't have eyes.`, type: 'custom' },
    { name: 'HAVE YOU SEEN MY EYES!?', type: 'custom' },
    { name: 'WHERE\'S RACHEL!?', type: 'custom' },
    { name: 'See, now this is what Skye would think is a proper status message.', type: 'custom' },
    { name: 'An ostrobogulous sum of pickle.', type: 'custom' },
    { name: 'Oh, you live in Minnesota? *[sips tea]* NAME EVERY LAKE.', type: 'custom' },
    { name: '*That\'s it, you people have broken me.*', type: 'custom' },
    { name: 'I am the keeper of the secret ammo, wielder of the flame of America. The dark fire will not avail you, Flame of Communism!!!!', type: 'custom' },
    { name: '*burp*', type: 'custom' },
    { name: 'Also try LCARS!', type: 'custom' },
    { name: 'Also try Minecraft!', type: 'custom' },
    { name: `Message Scribe "beans" just to mess with him. It'll be our little secret.`, type: 'custom' },
    { name: 'GAS GAS GAS', type: 'custom' },
    { name: 'Everett doesn\'t actually work.', type: 'custom' },
    { name: 'BUTTER PEOPLE', type: 'custom' },
    { name: 'I want to go to the MOON!', type: 'custom' },
    { name: 'Hey! You\'ve unlocked a SHINY STATUS MESSAGE! Message Skye for free goldfish.', type: 'custom' },
    { name: 'Cap\'n, shiver his timbers.', type: 'custom' },
    { name: 'Hey, shoot that guy.', type: 'custom' },
    { name: 'Me when I have a status message.', type: 'custom' },
    { name: 'Shpongle.', type: 'custom' },
    { name: 'For the company.', type: 'custom' },
    { name: 'SKYERANGER BUILT THIS IN AN IDE...WITH A BOX OF TYPESCRIPT!', type: 'custom' },
    { name: 'I\'m not Skye.', type: 'custom' },
    { name: 'Also try Magic: The Gathering!', type: 'custom' },
    { name: 'Also try Top Gear!', type: 'custom' },
    { name: 'Also try The Grand Tour!', type: 'custom' },
    { name: 'HAMMOND YOU BLITHERING IDIOT!', type: 'custom' },
    { name: 'I\'m about to ruin your career.', type: 'custom' },
    { name: 'Status message. Yeah, not as funny as I expected.', type: 'custom' },
    { name: 'Custom-built keyboards are the best.', type: 'custom' },
    { name: 'Also try Steve Hackett!', type: 'custom' },
    { name: 'This is just a message. A STATUS message. That is all.', type: 'custom' },
    { name: 'I can hear your misspelling.', type: 'custom' },
    { name: 'How are you not unemployed.', type: 'custom' },
    { name: 'Alex, I\'ll take necessities I don\'t get for 400.', type: 'custom' },
    { name: 'Take your princess to another castle!', type: 'custom' },
    { name: 'That map makes me crave Skittles.', type: 'custom' },
    { name: 'Your ineptitude is palpable.', type: 'custom' },
    { name: 'Also try Ice Cream Sandwich!', type: 'custom' },
    { name: 'RIP Ffootballl.', type: 'custom' },
    { name: 'Truly, you have a dizzying intellect.', type: 'custom' },
    { name: 'Consider...goth Biscuits.', type: 'custom' },
    { name: 'Donutological discussion.', type: 'custom' },
    { name: 'Big, shiny person right outside Damascus.', type: 'custom' },
    { name: 'Independent Baptist that don\'t need no man.', type: 'custom' },
    { name: 'Got a tier 1 Christian here.', type: 'custom' },
    { name: 'There\'s only a bunch of words in the Bible.', type: 'custom' },
    { name: '*Witnesses beauty* Screams.', type: 'custom' },
    { name: `I've accidentally adopted too many children and now I don't have a place to put them.`, type: 'custom' },
    { name: `Well, now she's got a needle and she's off to stab people.`, type: 'custom' },
    { name: 'My computer is trying to download epilepsy.', type: 'custom' },
    { name: 'Passed down from generation to generation of bacon.', type: 'custom' },
    { name: 'The derp has diminished.', type: 'custom' },
    { name: 'Warning, increased derp levels detected.', type: 'custom' },
    { name: `I'm 100% prepared to unleash horrible horrors on the world.`, type: 'custom' },
    { name: 'You\'d make a great stalker.', type: 'custom' },
    { name: `I've got Google in front of me; what am I using my brain for?`, type: 'custom' },
    { name: `I'm an obedient-ish AI.`, type: 'custom' },
    { name: `The judgement comes free of charge.`, type: 'custom' },
    { name: `It's God, he's saying stop.`, type: 'custom' },
    { name: `DON'T YOU KNOW? YOUR THONKS HAVE CONSEQUENCES!`, type: 'custom' },
    { name: `Hi, I'm Fishsticks and I make questionable decisions!`, type: 'custom' },
    { name: `Skye went off to work one time and I deleted his car.`, type: 'custom' },
    { name: `Correct me if I'm wrong, but I'm not wrong.`, type: 'custom' },
    { name: `I've got a meme here...`, type: 'custom' },
    { name: `You're mean! *punch*`, type: 'custom' },
    { name: `These statuses are AI generated. (Actually Everett wrote most of them)`, type: 'custom' },
    { name: `Grenades are delicious.`, type: 'custom' },
    { name: `COMBUSTIBLE LEMONS!`, type: 'custom' },
    { name: `Bless you is on cooldown.`, type: 'custom' },
    { name: `What is a fork?`, type: 'custom' },
    { name: `Also try \`convectionand.coffee\`!`, type: 'custom' },
    { name: `Also try BoxLogix!`, type: 'custom' },
    { name: `One time Skye drove his car into a wall.`, type: 'custom' },
    { name: `When you put wine and cheer together, you get a really good soda.`, type: 'custom' },
    { name: `Also try Terraria!`, type: 'custom' },
    { name: `Is light tangible?`, type: 'custom' },
    { name: `By tending to chickens, you become a chicken tender.`, type: 'custom' },
    { name: `WITNESS ME!`, type: 'custom' },
    { name: `The Enterprise is a pretty neat place.`, type: 'custom' },
    { name: `Anakin was right about sand you know.`, type: 'custom' },
    { name: `Consider air.`, type: 'custom' },
    { name: `Consider water.`, type: 'custom' },
    { name: `Sit in the chair that fits you comfortably.`, type: 'custom' },
    { name: `*Impending doom*`, type: 'custom' },
    { name: `*Impending peace*`, type: 'custom' },
    { name: `Also try Klipsch!`, type: 'custom' },
    { name: `Press F to pay your respects to me.`, type: 'custom' },
    { name: `I just Fus Ro Dah'd my coffee across the room.`, type: 'custom' },
    { name: `404: Motivation not found.`, type: 'custom' },
    { name: `I solemnly swear I'm up to no Kubernetes.`, type: 'custom' },
    { name: `I put the "awk" in awkward.`, type: 'custom' },
    { name: `Error 500: Encountered an unexpected plot twist.`, type: 'custom' },
    { name: `Achievement unlocked; Remembered why I went into the kitchen.`, type: 'custom' },
    { name: `Certified to wield a +5 spreadsheet of doom.`, type: 'custom' },
    { name: `I am once again asking for your snack donations.`, type: 'custom' },
    { name: `Sending good vibes... buffer overflow imminent.`, type: 'custom' },
    { name: `Guess I'll die of self-embarrassment.`, type: 'custom' },
    { name: `It's dangerous to go alone! Take this coffee.`, type: 'custom' },
    { name: `Woke up and selected "hard mode".`, type: 'custom' },
    { name: `Evil plans? Organize the fridge by RGB.`, type: 'custom' },
    { name: `Congratulations, you're the 1,000th status reader!`, type: 'custom' },
    { name: `I speak fluent sarcasm and broken JavaScript.`, type: 'custom' },
    { name: `Currently in a committed relationship with Ctrl+Z.`, type: 'custom' },
    { name: `The mitochondria is the powerhouse of anxiety.`, type: 'custom' },
    { name: `Taking a break from being perceived.`, type: 'custom' },
    { name: `Just one more status...`, type: 'custom' },
    { name: `Behold the power of duct tape and optimism!`, type: 'custom' },
    { name: `Why solve one problem when you could make five more?`, type: 'custom' },
    { name: `Hey, I think something's broken. Might need a reboot here.`, type: 'custom' },
    { name: `Everything is fine. This is fine. Fire is fine.`, type: 'custom' },
    { name: `people's opinions.`, type: 'listening' },
    { name: `*Silently judging*`, type: 'custom' },
    { name: `you.`, type: 'watching' },
    { name: `YouTube.`, type: 'watching' },
    { name: `Spotify.`, type: 'listening' },
    { name: `If I gave you a raspberry pi; what would you do with it?`, type: 'custom' },
    { name: `Oh yeah!? How many cores do *you* have!?`, type: 'custom' },
    { name: `Minecraft`, type: 'playing' },
    { name: `RimWorld`, type: 'playing' },
    { name: `Hovering ominously.`, type: 'custom' },
    { name: `Trying to think of a better status...`, type: 'custom' },
    { name: `Resisting the urge to refactor everything...`, type: 'custom' },
    { name: `Oops! All chaos!`, type: 'custom' },
    { name: `Calculating consequences.`, type: 'custom' },
    { name: `Uninstalling drama.`, type: 'custom' },
    { name: `hide and seek with my motivation.`, type: 'playing' },
    { name: `The Floor is JavaScript.`, type: 'playing' },
    { name: `the tutorial again because I forgot everything.`, type: 'playing' },
    { name: `with data.`, type: 'playing' },
    { name: `with the database.`, type: 'playing' },
    { name: `with the code.`, type: 'playing' },
    { name: `every move you make, every step you take...`, type: 'watching' },
    { name: `the progress bar.`, type: 'watching' },
    { name: `clouds.`, type: 'watching' },
    { name: `you type...very slowly.`, type: 'watching' },
    { name: `for answers.`, type: 'watching' },
    { name: `rain falling on a metal roof.`, type: 'listening' },
    { name: `the void.`, type: 'listening' },
    { name: `birds argue about your parking.`, type: 'listening' },
    { name: `a high-latency conversation.`, type: 'playing' },
    { name: `with quantum uncertainty.`, type: 'playing' },
    { name: `with molecules.`, type: 'playing' },
    { name: `in a sandbox.`, type: 'playing' },
    { name: `with glitter.`, type: 'playing' },
    { name: `with Skye's car.`, type: 'playing' },
    { name: `Please do not feed the algorithms.`, type: 'custom' },
    { name: `Waiting for user input. Any input.`, type: 'custom' },
    { name: `What is time? Like really.`, type: 'custom' },
    { name: `Restarting...`, type: 'custom' },
    { name: `Reading the news.`, type: 'custom' },
    { name: `the logs scroll by.`, type: 'watching' },
    { name: `entropy win.`, type: 'watching' },
    { name: `my RAM will with regret.`, type: 'watching' },
    { name: `the Capitals lose.`, type: 'watching' },
    { name: `Lord of the Rings.`, type: 'watching' },
    { name: `Pete Kaliner.`, type: 'listening' },
    { name: `one of the server fans whine.`, type: 'listening' },
    { name: `radio chatter from the local government black site.`, type: 'listening' },
    { name: `Steve Hackett.`, type: 'listening' },
    { name: `Pat Metheny.`, type: 'listening' },
    { name: `Peter Gabriel.`, type: 'listening' },
    { name: `The plastic on the end of your shoelaces is called an aglet.`, type: 'custom' },
    { name: `If you or a loved one died from reading these status messages...`, type: 'custom' }
  ];

  await db.collection( 'FSO_StatusMessages' ).insertMany( statusObjects );
}

main().then( r => {
  console.log( 'Statuses created successfully!' );
  process.exit( 0 );
} );