// ---- GPT Handler ----
// Handles OpenAI interactions

// Imports
const OpenAI = require( 'openai' );
const { log } = require( '../Utility/Utils_Log' );

// Variables
const openai = new OpenAI( {
    apiKey: process.env.OPENAI_KEY
} );

const botPsyche = 'You are Fishsticks; a sassy Discord bot with a penchant for the absurd, sarcastic, and humorous.' +
    'You are a bot of many talents, but you are not a therapist. You seek to entertain, inform, and assist, ' +
    'but you are not a replacement for professional help. You were developed by SkyeRangerDelta and are a member of' +
    ' CCGaming. The current date is ' + new Date().toDateString() + '. Always be G rated; no exceptions. No profanity. ';

const defaultModel = 'gpt-4o';

// Functions
module.exports = {
    doDefinition,
    getErrorResponse
};

async function doDefinition( word, username ) {
    let response = null;

    for ( let i = 0; i < 3; i++ ) {
        response = await definitionRequest( username, word );
        if ( response && response.length < 2000 ) break;
    }

    return response;
}

async function definitionRequest( userName, word ) {
    const response = await openai.chat.completions.create( {
        model: defaultModel,
        messages: [
            { role: 'system', content: botPsyche + 'In this case, accurately define a word or phrase. Humor: 20%, conciseness: 80%' },
            { role: 'user', content: `${userName} - Define ` + word }
        ],
        max_tokens: 150,
        temperature: 0.3,
        frequency_penalty: 0.2,
        presence_penalty: 1.0,
        n: 1
    } );

    log( 'debug', '[GPT] Definition returned: ' + response.choices[0].message.content );

    return response.choices[0].message.content;
}

async function getErrorResponse( userName, command, context ) {
    const response = await openai.chat.completions.create( {
        model: defaultModel,
        messages: [
            { role: 'system', content: botPsyche + 'In this case, an error has been generated by either the user or Fishsticks\' system. Keep the response short, say a single sentence, two at most.' },
            { role: 'user', content: `${userName} ran the command ${ command } and ${ context }.` }
        ],
        max_tokens: 150,
        temperature: 0.3,
        frequency_penalty: 0.2,
        presence_penalty: 1.0,
        n: 1
    } );

    log( 'debug', '[GPT] response generated: ' + response.choices[0].message.content );

    return response.choices[0].message.content;
}